In [1]:
theMatrix <- matrix(1:9, nrow=3)

In [2]:
theMatrix

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [4]:
# apply는 매트릭스를 받는다. 
apply(theMatrix,MARGIN = 2, sum) #마진은 컬럼으로 더해준다.
apply(theMatrix,MARGIN = 1, sum)

[1]  6 15 24

[1] 12 15 18

In [6]:
colSums(theMatrix)
rowSums(theMatrix)

[1]  6 15 24

[1] 12 15 18

In [7]:
theMatrix[2, 1] <- NA

In [12]:
theMatrix

apply(theMatrix, 1, sum) # NA가 있으면 더해지지 않는다. 
apply(theMatrix, 1, sum, na.rm=TRUE)
rowSums(theMatrix)
rowSums(theMatrix, na.rm=TRUE)

[,1] [,2] [,3]
[1,]  1   4    7   
[2,] NA   5    8   
[3,]  3   6    9

[1] 12 NA 18

[1] 12 13 18

[1] 12 NA 18

[1] 12 13 18

In [15]:
theList <- list(A=matrix(1:9, nrow=3), B=1:5, c=matrix(1:4, 2), D=2)
theList

$A
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$B
[1] 1 2 3 4 5

$c
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$D
[1] 2

In [17]:
lapply(theList, sum) # 리스트 안에 있는 모든 값들을 더해준다.
sapply(theList, sum) # vector를 최대한 반환한다

$A
[1] 45

$B
[1] 15

$c
[1] 10

$D
[1] 2

A  B  c  D 
45 15 10  2

In [18]:
theNames <- c("Jared", "Deb", "Paul")

In [19]:
lapply(theNames, nchar)

[[1]]
[1] 5

[[2]]
[1] 3

[[3]]
[1] 4

iteration을 어떻게 할까??

In [20]:
firstList <- list(A=matrix(1:16, 4), B=matrix(1:16, 2), c=1:5)
secondList <- list(A=matrix(1:16, 4), B=matrix(1:16, 8), c=15:1)

In [22]:
firstList
secondList

$A
     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16

$B
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]    1    3    5    7    9   11   13   15
[2,]    2    4    6    8   10   12   14   16

$c
[1] 1 2 3 4 5

$A
     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16

$B
     [,1] [,2]
[1,]    1    9
[2,]    2   10
[3,]    3   11
[4,]    4   12
[5,]    5   13
[6,]    6   14
[7,]    7   15
[8,]    8   16

$c
 [1] 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1

In [23]:
mapply(identical, firstList, secondList) 
# 각 요소별로 같은지 다른지 확인해준다. 
# identical은 동일한지 아닌지 확인해주는 function이다.

A     B     c 
 TRUE FALSE FALSE

In [24]:
simplefunc <- function(x, y){
    NROW(x) + NROW(y) # vector가 오면 그 길이를 반환해준다.
}

In [25]:
mapply(simplefunc, firstList, secondList) # 루프를 연산을 한 것을 볼 수 있다!

A  B  c 
 8 10 20

In [27]:
require(ggplot2)

Loading required package: ggplot2



In [28]:
data(diamonds)

In [29]:
head(diamonds)

carat cut       color clarity depth table price x    y    z   
1 0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31
3 0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31
4 0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63
5 0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75
6 0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48

In [30]:
mean(diamonds$price)

[1] 3932.8

In [31]:
aggregate(price ~ cut, diamonds, mean, na.rm=TRUE)
# cut에 따른 mean을 보겠다
# mean 말고도 다른 계산 함수를 넣을 수 있다. 

cut       price   
1 Fair      4358.758
2 Good      3928.864
3 Very Good 3981.760
4 Premium   4584.258
5 Ideal     3457.542

In [32]:
aggregate(price ~ cut + color, diamonds, mean) # cut과 color에 따라 mean을 본다. 

cut       color price   
1  Fair      D     4291.061
2  Good      D     3405.382
3  Very Good D     3470.467
4  Premium   D     3631.293
5  Ideal     D     2629.095
6  Fair      E     3682.312
7  Good      E     3423.644
8  Very Good E     3214.652
9  Premium   E     3538.914
10 Ideal     E     2597.550
11 Fair      F     3827.003
12 Good      F     3495.750
13 Very Good F     3778.820
14 Premium   F     4324.890
15 Ideal     F     3374.939
16 Fair      G     4239.255
17 Good      G     4123.482
18 Very Good G     3872.754
19 Premium   G     4500.742
20 Ideal     G     3720.706
21 Fair      H     5135.683
22 Good      H     4276.255
23 Very Good H     4535.390
24 Premium   H     5216.707
25 Ideal     H     3889.335
26 Fair      I     4685.446
27 Good      I     5078.533
28 Very Good I     5255.880
29 Premium   I     5946.181
30 Ideal     I     4451.970
31 Fair      J     4975.655
32 Good      J     4574.173
33 Very Good J     5103.513
34 Premium   J     6294.592
35 Ideal     J     4918.186

In [33]:
aggregate(cbind(price, carat) ~ cut, diamonds, mean) 
# price와 carat을 한꺼번에 볼수 있다.

cut       price    carat    
1 Fair      4358.758 1.0461366
2 Good      3928.864 0.8491847
3 Very Good 3981.760 0.8063814
4 Premium   4584.258 0.8919549
5 Ideal     3457.542 0.7028370

In [34]:
aggregate(cbind(price, carat) ~ cut + color, diamonds, mean)

cut       color price    carat    
1  Fair      D     4291.061 0.9201227
2  Good      D     3405.382 0.7445166
3  Very Good D     3470.467 0.6964243
4  Premium   D     3631.293 0.7215471
5  Ideal     D     2629.095 0.5657657
6  Fair      E     3682.312 0.8566071
7  Good      E     3423.644 0.7451340
8  Very Good E     3214.652 0.6763167
9  Premium   E     3538.914 0.7177450
10 Ideal     E     2597.550 0.5784012
11 Fair      F     3827.003 0.9047115
12 Good      F     3495.750 0.7759296
13 Very Good F     3778.820 0.7409612
14 Premium   F     4324.890 0.8270356
15 Ideal     F     3374.939 0.6558285
16 Fair      G     4239.255 1.0238217
17 Good      G     4123.482 0.8508955
18 Very Good G     3872.754 0.7667986
19 Premium   G     4500.742 0.8414877
20 Ideal     G     3720.706 0.7007146
21 Fair      H     5135.683 1.2191749
22 Good      H     4276.255 0.9147293
23 Very Good H     4535.390 0.9159485
24 Premium   H     5216.707 1.0164492
25 Ideal     H     3889.335 0.7995249
26 Fair      I     4685.446 1.1980571
27 Good      I     5078.533 1.0572222
28 Very Good I     5255.880 1.0469518
29 Premium   I     5946.181 1.1449370
30 Ideal     I     4451.970 0.9130291
31 Fair      J     4975.655 1.3411765
32 Good      J     4574.173 1.0995440
33 Very Good J     5103.513 1.1332153
34 Premium   J     6294.592 1.2930941
35 Ideal     J     4918.186 1.0635937

In [37]:
require(plyr)
# plyr 패키지를 이용하자

Loading required package: plyr



In [38]:
head(baseball)

id        year stint team lg g  ab  r  h  X2b ⋯ rbi sb cs bb so ibb hbp sh
4   ansonca01 1871 1     RC1     25 120 29 39 11  ⋯ 16  6  2  2  1  NA  NA  NA
44  forceda01 1871 1     WS3     32 162 45 45  9  ⋯ 29  8  0  4  0  NA  NA  NA
68  mathebo01 1871 1     FW1     19  89 15 24  3  ⋯ 10  2  1  2  0  NA  NA  NA
99  startjo01 1871 1     NY2     33 161 35 58  5  ⋯ 34  4  2  3  0  NA  NA  NA
102 suttoez01 1871 1     CL1     29 128 35 45  3  ⋯ 23  3  1  1  0  NA  NA  NA
106 whitede01 1871 1     CL1     29 146 40 47  6  ⋯ 21  2  2  4  1  NA  NA  NA
    sf gidp
4   NA NA  
44  NA NA  
68  NA NA  
99  NA NA  
102 NA NA  
106 NA NA

In [39]:
any(is.na(baseball$sf)) # na가 있는지 확인

[1] TRUE

In [40]:
baseball$sf[baseball$year < 1954] <- 0

In [44]:
any(is.na(baseball$hbp))

[1] FALSE

In [43]:
baseball$hbp[is.na(baseball$hbp)] <- 0 

In [45]:
baseball <- baseball[baseball$ab >= 50, ]

In [46]:
baseball$OBP <- with(baseball, (h + bb + hbp) / (ab + bb + hbp + sf)) 
# with 문 (데이터, 공식 )
# 아주 편리하다.

In [47]:
baseball

id        year stint team lg g   ab  r  h   X2b ⋯ sb cs bb  so  ibb hbp
4     ansonca01 1871 1     RC1     25  120 29  39 11  ⋯ 6  2   2  1   NA  0  
44    forceda01 1871 1     WS3     32  162 45  45  9  ⋯ 8  0   4  0   NA  0  
68    mathebo01 1871 1     FW1     19   89 15  24  3  ⋯ 2  1   2  0   NA  0  
99    startjo01 1871 1     NY2     33  161 35  58  5  ⋯ 4  2   3  0   NA  0  
102   suttoez01 1871 1     CL1     29  128 35  45  3  ⋯ 3  1   1  0   NA  0  
106   whitede01 1871 1     CL1     29  146 40  47  6  ⋯ 2  2   4  1   NA  0  
113   yorkto01  1871 1     TRO     29  145 36  37  5  ⋯ 2  2   9  1   NA  0  
121   ansonca01 1872 1     PH1     46  217 60  90 10  ⋯ 6  6  16  3   NA  0  
143   burdoja01 1872 1     BR2     37  174 26  46  3  ⋯ 0  1   1  1   NA  0  
167   forceda01 1872 1     TRO     25  130 40  53 11  ⋯ 2  2   1  0   NA  0  
168   forceda01 1872 2     BL1     19   95 29  41  2  ⋯ 3  0   1  0   NA  0  
209   mathebo01 1872 1     BL1     50  223 36  50  1  ⋯ 1  1   3  2   NA  0  
227   nelsoca01 1872 2     BR1     18   76 12  19  2  ⋯ 1  0   2  2   NA  0  
229   orourji01 1872 1     MID     23  101 25  31  4  ⋯ 1  0   2  0   NA  0  
249   startjo01 1872 1     NY2     55  282 62  76  4  ⋯ 3  3   0  0   NA  0  
252   suttoez01 1872 1     CL1     22  107 30  30  6  ⋯ 1  0   1  1   NA  0  
259   whitede01 1872 1     CL1     22  109 21  37  2  ⋯ 0  0   4  1   NA  0  
268   yorkto01  1872 1     BL1     51  248 66  66 10  ⋯ 2  1   4  1   NA  0  
276   ansonca01 1873 1     PH1     52  254 53 101  9  ⋯ 0  2   5  1   NA  0  
293   burdoja01 1873 1     BR2     55  245 56  62  7  ⋯ 3  1   7  4   NA  0  
314   forceda01 1873 1     BL1     49  234 77  86  8  ⋯ 1  0   9  0   NA  0  
318   gerhajo01 1873 1     WS5     13   56  6  12  3  ⋯ 0  0   0  5   NA  0  
327   hinespa01 1873 1     WS5     39  181 33  60  6  ⋯ 0  1   1  1   NA  0  
344   mathebo01 1873 1     NY2     52  223 40  43  3  ⋯ 1  1  10  3   NA  0  
353   nelsoca01 1873 1     NY2     36  168 28  55  4  ⋯ 2  0   1  2   NA  0  
355   orourji01 1873 1     BS1     57  280 79  98 19  ⋯ 4  2  14  1   NA  0  
375   snydepo01 1873 1     WS5     28  108 16  21  2  ⋯ 0  1   3  3   NA  0  
377   startjo01 1873 1     NY2     53  251 42  67  8  ⋯ 1  0   4  0   NA  0  
380   suttoez01 1873 1     PH1     51  242 51  81  7  ⋯ 1  3   2  2   NA  0  
386   whitede01 1873 1     BS1     60  310 79 121 15  ⋯ 6  2   0  2   NA  0  
⋮     ⋮         ⋮    ⋮     ⋮    ⋮  ⋮   ⋮   ⋮  ⋮   ⋮   ⋱ ⋮  ⋮  ⋮   ⋮   ⋮   ⋮  
89385 sandere02 2007 1     KCA  AL  24  73 12  23  7  ⋯  0 1   11  15  0   1 
89389 rodriiv01 2007 1     DET  AL 129 502 50 141 31  ⋯  2 2    9  96  1   1 
89396 ramirma02 2007 1     BOS  AL 133 483 84 143 33  ⋯  0 0   71  92 13   7 
89398 piazzmi01 2007 1     OAK  AL  83 309 33  85 17  ⋯  0 0   18  61  0   0 
89400 perezne01 2007 1     DET  AL  33  64  5  11  3  ⋯  0 0    4   8  0   0 
89412 moyerja01 2007 1     PHI  NL  33  73  4   9  2  ⋯  0 0    2  26  0   0 
89425 maddugr01 2007 1     SDN  NL  33  62  2   9  2  ⋯  1 0    1  19  0   0 
89429 loftoke01 2007 2     CLE  AL  52 173 24  49  9  ⋯  2 3   17  23  0   0 
89430 loftoke01 2007 1     TEX  AL  84 317 62  96 16  ⋯ 21 4   39  28  1   2 
89438 kleskry01 2007 1     SFN  NL 116 362 51  94 27  ⋯  5 1   46  68  2   1 
89439 kentje01  2007 1     LAN  NL 136 494 78 149 36  ⋯  1 3   57  61  4   5 
89462 griffke02 2007 1     CIN  NL 144 528 78 146 24  ⋯  6 1   85  99 14   1 
89463 greensh01 2007 1     NYN  NL 130 446 62 130 30  ⋯ 11 1   37  62  4   5 
89464 graffto01 2007 1     MIL  NL  86 231 34  55  8  ⋯  0 1   24  44  6   3 
89466 gonzalu01 2007 1     LAN  NL 139 464 70 129 23  ⋯  6 2   56  56  4   4 
89467 gomezch02 2007 2     CLE  AL  19  53  4  15  2  ⋯  0 0    0   6  0   0 
89468 gomezch02 2007 1     BAL  AL  73 169 17  51 10  ⋯  1 2   10  20  1   0 
89469 glavito02 2007 1     NYN  NL  33  56  3  12  1  ⋯  0 0    6   5  0   0 
89473 floydcl01 2007 1     CHN  NL 108 282 40  80 10  ⋯  0 0   35  47  5   5 
89474 finlest01 2007 1     C

In [51]:
obp <- function(data)
{
    c(OBP=with(data, sum(h + bb + hbp)  / sum(ab + bb + hbp + sf)))
}

In [52]:
careerOBP <- ddply(baseball, .variables = "id", obp) 
# ddply는 데이터를 쪼개는데 좋다

In [53]:
head(careerOBP)

id        OBP      
1 aaronha01 0.3739493
2 adairje01 0.2922746
3 adamsba01 0.2550694
4 adamsbo03 0.3403342
5 adcocjo01 0.3368726
6 aguilri01 0.2037037

In [56]:
careerOBP <- careerOBP[order(careerOBP$OBP, decreasing=TRUE), ]
# 이렇게 해주면 순서를 정령해준다

In [57]:
head(careerOBP)

id        OBP      
1089 willite01 0.4816861
875  ruthba01  0.4742209
658  mcgrajo01 0.4657478
356  gehrilo01 0.4477848
85   bondsba01 0.4444622
476  hornsro01 0.4339068

In [58]:
theList <- list(A=matrix(1:9, 3), B=1:5, C=matrix(1:4, 2), D=2)
theList

$A
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$B
[1] 1 2 3 4 5

$C
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$D
[1] 2

In [61]:
lapply(theList, sum)
llply(theList, sum)
identical(lapply(theList, sum), llply(theList, sum))

$A
[1] 45

$B
[1] 15

$C
[1] 10

$D
[1] 2

$A
[1] 45

$B
[1] 15

$C
[1] 10

$D
[1] 2

[1] TRUE

In [62]:
sapply(theList, sum) # 벡터를 반환. 이름이 있다. 
laply(theList, sum) # 이거는 벡터를 반환. 대신 이름이 없다. 

A  B  C  D 
45 15 10  2

[1] 45 15 10  2

In [64]:
aggregate(price ~ cut, diamonds, each(mean, median)) 
# each를 이용해 두 가지 연산을 다 할 수 있다. 

cut       price           
1 Fair      4358.758, 3282.0
2 Good      3928.864, 3050.5
3 Very Good 3981.760, 2648.0
4 Premium   4584.258, 3185.0
5 Ideal     3457.542, 1810.0

In [65]:
numcolwise(sum, na.rm=TRUE)(diamonds) # numeric 컬럼들에 대해서만 진행된다. 

carat    depth   table   price     x        y        z       
1 43040.87 3330763 3099240 212135217 309138.6 309320.3 190879.3

In [66]:
sapply(diamonds[, sapply(diamonds, is.numeric)], sum) # 이렇게도 가능
# 그러나 numcolwise가 더 편하다. 

carat        depth        table        price            x            y 
    43040.87   3330762.90   3099240.50 212135217.00    309138.62    309320.33 
           z 
   190879.30

In [67]:
sport <- c("Hockey", "Baseball","Football")
league <- c("NHL", "MLB", "NFL")
trophy <- c("Stanley Cup", "Comissioner's Trophy", "Vince Lombardi Trophy")

In [68]:
sports1 <- cbind(sport, league, trophy)

In [69]:
sports1

sport    league trophy               
[1,] Hockey   NHL    Stanley Cup          
[2,] Baseball MLB    Comissioner's Trophy 
[3,] Football NFL    Vince Lombardi Trophy

In [70]:
sports2 <- data.frame(sport=c("Basketball","Golf"),
                     league=c("NBA","PGA"),
                     trophy=c("Larry O'Brien championship Trophy", "Wanamaker Trophy"))

In [71]:
sports2

sport      league trophy                           
1 Basketball NBA    Larry O'Brien championship Trophy
2 Golf       PGA    Wanamaker Trophy

In [72]:
rbind(sports1, sports2)

sport      league trophy                           
1 Hockey     NHL    Stanley Cup                      
2 Baseball   MLB    Comissioner's Trophy             
3 Football   NFL    Vince Lombardi Trophy            
4 Basketball NBA    Larry O'Brien championship Trophy
5 Golf       PGA    Wanamaker Trophy

In [1]:
codes <- read.table("countryCodes.csv", header=TRUE, sep=",", stringsAsFactors = FALSE)

In [2]:
countries <- read.table("GovType.csv", header=TRUE, sep=",", stringsAsFactors = FALSE)

In [4]:
head(countries) # View도 굉장히 편리하다

Country            
1 Afghanistan        
2 Albania            
3 Algeria            
4 Andorra            
5 Angola             
6 Antigua and Barbuda
  GovernmentType                                                                            
1 Islamic republic                                                                          
2 parliamentary democracy                                                                   
3 republic                                                                                  
4 parliamentary democracy                                                                   
5 republic; multiparty presidential regime                                                  
6 constitutional monarchy with a parliamentary system of government and a Commonwealth realm

In [8]:
View(codes)

Code Country.name                         Year ccTLD ISO.3166.2   
1   AD   Andorra                              1974 .ad   ISO 3166-2:AD
2   AE   United Arab Emirates                 1974 .ae   ISO 3166-2:AE
3   AF   Afghanistan                          1974 .af   ISO 3166-2:AF
4   AG   Antigua and Barbuda                  1974 .ag   ISO 3166-2:AG
5   AI   Anguilla                             1983 .ai   ISO 3166-2:AI
6   AL   Albania                              1974 .al   ISO 3166-2:AL
7   AM   Armenia                              1992 .am   ISO 3166-2:AM
8   AO   Angola                               1974 .ao   ISO 3166-2:AO
9   AQ   Antarctica                           1974 .aq   ISO 3166-2:AQ
10  AR   Argentina                            1974 .ar   ISO 3166-2:AR
11  AS   American Samoa                       1974 .as   ISO 3166-2:AS
12  AT   Austria                              1974 .at   ISO 3166-2:AT
13  AU   Australia                            1974 .au   ISO 3166-2:AU
14  AW   Aruba                                1986 .aw   ISO 3166-2:AW
15  AX   Aland Islands !Ã\u0085land Islands   2004 .ax   ISO 3166-2:AX
16  AZ   Azerbaijan                           1992 .az   ISO 3166-2:AZ
17  BA   Bosnia and Herzegovina               1992 .ba   ISO 3166-2:BA
18  BB   Barbados                             1974 .bb   ISO 3166-2:BB
19  BD   Bangladesh                           1974 .bd   ISO 3166-2:BD
20  BE   Belgium                              1974 .be   ISO 3166-2:BE
21  BF   Burkina Faso                         1984 .bf   ISO 3166-2:BF
22  BG   Bulgaria                             1974 .bg   ISO 3166-2:BG
23  BH   Bahrain                              1974 .bh   ISO 3166-2:BH
24  BI   Burundi                              1974 .bi   ISO 3166-2:BI
25  BJ   Benin                                1977 .bj   ISO 3166-2:BJ
26  BL   Saint Barthélemy                    2007 .bl   ISO 3166-2:BL
27  BM   Bermuda                              1974 .bm   ISO 3166-2:BM
28  BN   Brunei Darussalam                    1974 .bn   ISO 3166-2:BN
29  BO   Bolivia, Plurinational State of      1974 .bo   ISO 3166-2:BO
30  BQ   Bonaire, Sint Eustatius and Saba     2010 .bq   ISO 3166-2:BQ
⋮   ⋮    ⋮                                    ⋮    ⋮     ⋮            
220 TK   Tokelau                              1974 .tk   ISO 3166-2:TK
221 TL   Timor-Leste                          2002 .tl   ISO 3166-2:TL
222 TM   Turkmenistan                         1992 .tm   ISO 3166-2:TM
223 TN   Tunisia                              1974 .tn   ISO 3166-2:TN
224 TO   Tonga                                1974 .to   ISO 3166-2:TO
225 TR   Turkey                               1974 .tr   ISO 3166-2:TR
226 TT   Trinidad and Tobago                  1974 .tt   ISO 3166-2:TT
227 TV   Tuvalu                               1979 .tv   ISO 3166-2:TV
228 TW   Taiwan, Province of China            1974 .tw   ISO 3166-2:TW
229 TZ   Tanzania, United Republic of         1974 .tz   ISO 3166-2:TZ
230 UA   Ukraine                              1974 .ua   ISO 3166-2:UA
231 UG   Uganda                               1974 .ug   ISO 3166-2:UG
232 UM   United States Minor Outlying Islands 1986 .um   ISO 3166-2:UM
233 US   United States                        1974 .us   ISO 3166-2:US
234 UY   Uruguay                              1974 .uy   ISO 3166-2:UY
235 UZ   Uzbekistan                           1992 .uz   ISO 3166-2:UZ
236 VA   Holy See (Vatican City State)        1974 .va   ISO 3166-2:VA
237 VC   Saint Vincent and the Grenadines     1974 .vc   ISO 3166-2:VC
238 VE   Venezuela, Bolivarian Republic of    1974 .ve   ISO 3166-2:VE
239 VG   Virgin Islands, British              1974 .vg   ISO 3166-2:VG
240 VI   Virgin Islands, U.S.                 1974 .vi   ISO 3166-2:VI
241 VN   Viet Nam                             1974 .vn   ISO 3166-2:VN
242 VU   Vanuatu                              1980 .vu   ISO 3166-2:VU
243 WF   Wallis and Futuna                    1974 .wf   ISO 3166-2:WF
244 WS   Samoa              

In [10]:
countryMerged <- merge(x=codes, y=countries, by.x="Country.name", by.y="Country")
# 기본적으로 merge라는 기능이 있다. 
# x는 왼쪽, y는 오른쪽

In [11]:
countryMerged

Country.name           Code Year ccTLD      ISO.3166.2   
1   Afghanistan            AF   1974 .af        ISO 3166-2:AF
2   Albania                AL   1974 .al        ISO 3166-2:AL
3   Algeria                DZ   1974 .dz        ISO 3166-2:DZ
4   Andorra                AD   1974 .ad        ISO 3166-2:AD
5   Angola                 AO   1974 .ao        ISO 3166-2:AO
6   Antigua and Barbuda    AG   1974 .ag        ISO 3166-2:AG
7   Argentina              AR   1974 .ar        ISO 3166-2:AR
8   Armenia                AM   1992 .am        ISO 3166-2:AM
9   Aruba                  AW   1986 .aw        ISO 3166-2:AW
10  Australia              AU   1974 .au        ISO 3166-2:AU
11  Austria                AT   1974 .at        ISO 3166-2:AT
12  Azerbaijan             AZ   1992 .az        ISO 3166-2:AZ
13  Bahrain                BH   1974 .bh        ISO 3166-2:BH
14  Bangladesh             BD   1974 .bd        ISO 3166-2:BD
15  Barbados               BB   1974 .bb        ISO 3166-2:BB
16  Belarus                BY   1974 .by        ISO 3166-2:BY
17  Belgium                BE   1974 .be        ISO 3166-2:BE
18  Belize                 BZ   1974 .bz        ISO 3166-2:BZ
19  Benin                  BJ   1977 .bj        ISO 3166-2:BJ
20  Bermuda                BM   1974 .bm        ISO 3166-2:BM
21  Bhutan                 BT   1974 .bt        ISO 3166-2:BT
22  Bosnia and Herzegovina BA   1992 .ba        ISO 3166-2:BA
23  Botswana               BW   1974 .bw        ISO 3166-2:BW
24  Brazil                 BR   1974 .br        ISO 3166-2:BR
25  Bulgaria               BG   1974 .bg        ISO 3166-2:BG
26  Burkina Faso           BF   1984 .bf        ISO 3166-2:BF
27  Burundi                BI   1974 .bi        ISO 3166-2:BI
28  Cambodia               KH   1974 .kh        ISO 3166-2:KH
29  Cameroon               CM   1974 .cm        ISO 3166-2:CM
30  Canada                 CA   1974 .ca        ISO 3166-2:CA
⋮   ⋮                      ⋮    ⋮    ⋮          ⋮            
161 South Sudan            SS   2011 .ss        ISO 3166-2:SS
162 Spain                  ES   1974 .es        ISO 3166-2:ES
163 Sri Lanka              LK   1974 .lk        ISO 3166-2:LK
164 Sudan                  SD   1974 .sd        ISO 3166-2:SD
165 Suriname               SR   1974 .sr        ISO 3166-2:SR
166 Swaziland              SZ   1974 .sz        ISO 3166-2:SZ
167 Sweden                 SE   1974 .se        ISO 3166-2:SE
168 Switzerland            CH   1974 .ch        ISO 3166-2:CH
169 Tajikistan             TJ   1992 .tj        ISO 3166-2:TJ
170 Thailand               TH   1974 .th        ISO 3166-2:TH
171 Timor-Leste            TL   2002 .tl        ISO 3166-2:TL
172 Togo                   TG   1974 .tg        ISO 3166-2:TG
173 Tonga                  TO   1974 .to        ISO 3166-2:TO
174 Trinidad and Tobago    TT   1974 .tt        ISO 3166-2:TT
175 Tunisia                TN   1974 .tn        ISO 3166-2:TN
176 Turkey                 TR   1974 .tr        ISO 3166-2:TR
177 Turkmenistan           TM   1992 .tm        ISO 3166-2:TM
178 Tuvalu                 TV   1979 .tv        ISO 3166-2:TV
179 Uganda                 UG   1974 .ug        ISO 3166-2:UG
180 Ukraine                UA   1974 .ua        ISO 3166-2:UA
181 United Arab Emirates   AE   1974 .ae        ISO 3166-2:AE
182 United Kingdom         GB   1974 .gb\n(.uk) ISO 3166-2:GB
183 United States          US   1974 .us        ISO 3166-2:US
184 Uruguay                UY   1974 .uy        ISO 3166-2:UY
185 Uzbekistan             UZ   1992 .uz        ISO 3166-2:UZ
186 Vanuatu                VU   1980 .vu        ISO 3166-2:VU
187 Wallis and Futuna      WF   1974 .wf        ISO 3166-2:WF
188 Yemen                  YE   1974 .ye        ISO 3166-2:YE
189 Zambia                 ZM   1974 .zm        ISO 3166-2:ZM
190 Zimbabwe               ZW   1980 .zw        ISO 3166-2:ZW
    Notes                                                                                                                                                       

In [14]:
# plyr에서 joint 쓰면 훨씬 편하다. 
# 그렇지만 컬럼이 같은 이름이 있어야 한다..
require(plyr)
codes <- rename(codes, c(Country.name="Country"))# rename으로 컬럼명 바로 변경 가능하다. 
CountryJoined <- join(x=codes, y=countries, by="Country")

Loading required package: plyr



In [15]:
CountryJoined 
# 잘 합쳐진 것을 볼 수 있다.

Code Country                              Year ccTLD ISO.3166.2   
1   AD   Andorra                              1974 .ad   ISO 3166-2:AD
2   AE   United Arab Emirates                 1974 .ae   ISO 3166-2:AE
3   AF   Afghanistan                          1974 .af   ISO 3166-2:AF
4   AG   Antigua and Barbuda                  1974 .ag   ISO 3166-2:AG
5   AI   Anguilla                             1983 .ai   ISO 3166-2:AI
6   AL   Albania                              1974 .al   ISO 3166-2:AL
7   AM   Armenia                              1992 .am   ISO 3166-2:AM
8   AO   Angola                               1974 .ao   ISO 3166-2:AO
9   AQ   Antarctica                           1974 .aq   ISO 3166-2:AQ
10  AR   Argentina                            1974 .ar   ISO 3166-2:AR
11  AS   American Samoa                       1974 .as   ISO 3166-2:AS
12  AT   Austria                              1974 .at   ISO 3166-2:AT
13  AU   Australia                            1974 .au   ISO 3166-2:AU
14  AW   Aruba                                1986 .aw   ISO 3166-2:AW
15  AX   Aland Islands !Ã\u0085land Islands   2004 .ax   ISO 3166-2:AX
16  AZ   Azerbaijan                           1992 .az   ISO 3166-2:AZ
17  BA   Bosnia and Herzegovina               1992 .ba   ISO 3166-2:BA
18  BB   Barbados                             1974 .bb   ISO 3166-2:BB
19  BD   Bangladesh                           1974 .bd   ISO 3166-2:BD
20  BE   Belgium                              1974 .be   ISO 3166-2:BE
21  BF   Burkina Faso                         1984 .bf   ISO 3166-2:BF
22  BG   Bulgaria                             1974 .bg   ISO 3166-2:BG
23  BH   Bahrain                              1974 .bh   ISO 3166-2:BH
24  BI   Burundi                              1974 .bi   ISO 3166-2:BI
25  BJ   Benin                                1977 .bj   ISO 3166-2:BJ
26  BL   Saint Barthélemy                    2007 .bl   ISO 3166-2:BL
27  BM   Bermuda                              1974 .bm   ISO 3166-2:BM
28  BN   Brunei Darussalam                    1974 .bn   ISO 3166-2:BN
29  BO   Bolivia, Plurinational State of      1974 .bo   ISO 3166-2:BO
30  BQ   Bonaire, Sint Eustatius and Saba     2010 .bq   ISO 3166-2:BQ
⋮   ⋮    ⋮                                    ⋮    ⋮     ⋮            
220 TK   Tokelau                              1974 .tk   ISO 3166-2:TK
221 TL   Timor-Leste                          2002 .tl   ISO 3166-2:TL
222 TM   Turkmenistan                         1992 .tm   ISO 3166-2:TM
223 TN   Tunisia                              1974 .tn   ISO 3166-2:TN
224 TO   Tonga                                1974 .to   ISO 3166-2:TO
225 TR   Turkey                               1974 .tr   ISO 3166-2:TR
226 TT   Trinidad and Tobago                  1974 .tt   ISO 3166-2:TT
227 TV   Tuvalu                               1979 .tv   ISO 3166-2:TV
228 TW   Taiwan, Province of China            1974 .tw   ISO 3166-2:TW
229 TZ   Tanzania, United Republic of         1974 .tz   ISO 3166-2:TZ
230 UA   Ukraine                              1974 .ua   ISO 3166-2:UA
231 UG   Uganda                               1974 .ug   ISO 3166-2:UG
232 UM   United States Minor Outlying Islands 1986 .um   ISO 3166-2:UM
233 US   United States                        1974 .us   ISO 3166-2:US
234 UY   Uruguay                              1974 .uy   ISO 3166-2:UY
235 UZ   Uzbekistan                           1992 .uz   ISO 3166-2:UZ
236 VA   Holy See (Vatican City State)        1974 .va   ISO 3166-2:VA
237 VC   Saint Vincent and the Grenadines     1974 .vc   ISO 3166-2:VC
238 VE   Venezuela, Bolivarian Republic of    1974 .ve   ISO 3166-2:VE
239 VG   Virgin Islands, British              1974 .vg   ISO 3166-2:VG
240 VI   Virgin Islands, U.S.                 1974 .vi   ISO 3166-2:VI
241 VN   Viet Nam                             1974 .vn   ISO 3166-2:VN
242 VU   Vanuatu                              1980 .vu   ISO 3166-2:VU
243 WF   Wallis and Futuna                    1974 .wf   ISO 3166-2:WF
244 WS   Samoa              

In [18]:
require(reshape2)
head(airquality)

Loading required package: reshape2



Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [20]:
airMelt <- melt(airquality, id=c("Month","Day"), 
                value.name="Value", 
                variable.name="metric")

In [21]:
head(airMelt)

Month Day metric Value
1 5     1   Ozone  41   
2 5     2   Ozone  36   
3 5     3   Ozone  12   
4 5     4   Ozone  18   
5 5     5   Ozone  NA   
6 5     6   Ozone  28

In [23]:
dim(airquality)
dim(airMelt)
# 데이터가 길어졌다.

[1] 153   6

[1] 612   4

In [25]:
airCast<-dcast(airMelt, Month + Day ~ metric, value.var="Value") 
# dcast melt의 반대다

In [26]:
head(airCast)

Month Day Ozone Solar.R Wind Temp
1 5     1   41    190      7.4 67  
2 5     2   36    118      8.0 72  
3 5     3   12    149     12.6 74  
4 5     4   18    313     11.5 62  
5 5     5   NA     NA     14.3 56  
6 5     6   28     NA     14.9 66

In [27]:
airCast <- airCast[, c("Ozone", "Solar.R", "Wind", "Month", "Day")]

In [29]:
head(airCast, 3)
# 이런 식으로 데이터를 변환하는 것에 익숙해져야 한다. 

Ozone Solar.R Wind Month Day
1 41    190      7.4 5     1  
2 36    118      8.0 5     2  
3 12    149     12.6 5     3

이제 대망의 tidyr에 대해서 배워보자.

In [30]:
head(airquality)

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [33]:
require(tidyr)
airGather <- airquality %>% gather(Metric,#metric이라는 새로운 데이터
                                                  Value, 
                                                  -c(Month, Day))

In [34]:
airGather # 잘 변했다.

Month Day Metric Value
1   5      1  Ozone   41  
2   5      2  Ozone   36  
3   5      3  Ozone   12  
4   5      4  Ozone   18  
5   5      5  Ozone   NA  
6   5      6  Ozone   28  
7   5      7  Ozone   23  
8   5      8  Ozone   19  
9   5      9  Ozone    8  
10  5     10  Ozone   NA  
11  5     11  Ozone    7  
12  5     12  Ozone   16  
13  5     13  Ozone   11  
14  5     14  Ozone   14  
15  5     15  Ozone   18  
16  5     16  Ozone   14  
17  5     17  Ozone   34  
18  5     18  Ozone    6  
19  5     19  Ozone   30  
20  5     20  Ozone   11  
21  5     21  Ozone    1  
22  5     22  Ozone   11  
23  5     23  Ozone    4  
24  5     24  Ozone   32  
25  5     25  Ozone   NA  
26  5     26  Ozone   NA  
27  5     27  Ozone   NA  
28  5     28  Ozone   23  
29  5     29  Ozone   45  
30  5     30  Ozone  115  
⋮   ⋮     ⋮   ⋮      ⋮    
583 9      1  Temp   91   
584 9      2  Temp   92   
585 9      3  Temp   93   
586 9      4  Temp   93   
587 9      5  Temp   87   
588 9      6  Temp   84   
589 9      7  Temp   80   
590 9      8  Temp   78   
591 9      9  Temp   75   
592 9     10  Temp   73   
593 9     11  Temp   81   
594 9     12  Temp   76   
595 9     13  Temp   77   
596 9     14  Temp   71   
597 9     15  Temp   71   
598 9     16  Temp   78   
599 9     17  Temp   67   
600 9     18  Temp   76   
601 9     19  Temp   68   
602 9     20  Temp   82   
603 9     21  Temp   64   
604 9     22  Temp   71   
605 9     23  Temp   81   
606 9     24  Temp   69   
607 9     25  Temp   63   
608 9     26  Temp   70   
609 9     27  Temp   77   
610 9     28  Temp   75   
611 9     29  Temp   76   
612 9     30  Temp   68

In [36]:
airSpread <- airGather %>% spread(Metric,#Key
                                                     Value )#value)

In [37]:
head(airSpread)

Month Day Ozone Solar.R Temp Wind
1 5     1   41    190     67    7.4
2 5     2   36    118     72    8.0
3 5     3   12    149     74   12.6
4 5     4   18    313     62   11.5
5 5     5   NA     NA     56   14.3
6 5     6   28     NA     66   14.9

Group operation
-- 결국 데이터를 정리하는 것은 이렇게 해야 한다...

In [39]:
data("diamonds", package="ggplot2")

In [40]:
head(diamonds)

carat cut       color clarity depth table price x    y    z   
1 0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31
3 0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31
4 0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63
5 0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75
6 0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48

In [42]:
aggregate(diamonds$price, by=list(diamonds$cut), mean)

Group.1   x       
1 Fair      4358.758
2 Good      3928.864
3 Very Good 3981.760
4 Premium   4584.258
5 Ideal     3457.542

In [44]:
aggregate(price ~ cut, diamonds , mean) 
# 이렇게도 가능하지만 느릴 수 있다. 
# 데이터가 클 경우 그렇다.

cut       price   
1 Fair      4358.758
2 Good      3928.864
3 Very Good 3981.760
4 Premium   4584.258
5 Ideal     3457.542

In [45]:
# tapply를 배워보자. 
# 데이터 aggregation용으로 좋다.
tapply(diamonds$price, INDEX = diamonds$cut, mean)
# 벡터를 반환하는 것을 볼 수 있다. 

Fair      Good Very Good   Premium     Ideal 
 4358.758  3928.864  3981.760  4584.258  3457.542

In [46]:
require(plyr)

In [ ]:
ddply 
llply
dlply
adply

In [49]:
ddply(diamonds, "cut", summarize, Price=mean(price)) 
# Price라고 써준 것에 주목. 구분 위해서 그런 것

cut       Price   
1 Fair      4358.758
2 Good      3928.864
3 Very Good 3981.760
4 Premium   4584.258
5 Ideal     3457.542

In [50]:
daply(diamonds, "cut", summarize, Price=mean(price))
# 벡터를 반환한다. 

$Fair
[1] 4358.758

$Good
[1] 3928.864

$`Very Good`
[1] 3981.76

$Premium
[1] 4584.258

$Ideal
[1] 3457.542

In [56]:
head(diamonds)
require(doParallel)

carat cut       color clarity depth table price x    y    z   
1 0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31
3 0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31
4 0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63
5 0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75
6 0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48

In [57]:
# multiprocessing방법!

cl <- makeCluster(2)
registerDoParallel(cl)

In [58]:
ddply(diamonds, "cut", function(x) mean(x$price), .parallel = TRUE)

Warning message:
“<anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
”
Warning message:
“<anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
”


cut       V1      
1 Fair      4358.758
2 Good      3928.864
3 Very Good 3981.760
4 Premium   4584.258
5 Ideal     3457.542

In [59]:
require(data.table)
head(diamonds)

Loading required package: data.table


Attaching package: ‘data.table’


The following objects are masked from ‘package:reshape2’:

    dcast, melt




carat cut       color clarity depth table price x    y    z   
1 0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31
3 0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31
4 0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63
5 0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75
6 0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48

In [60]:
diaDT <- data.table(diamonds)
diaDT

carat cut       color clarity depth table price x    y    z   
1     0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43
2     0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31
3     0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31
4     0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63
5     0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75
6     0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48
7     0.24  Very Good I     VVS1    62.3  57    336   3.95 3.98 2.47
8     0.26  Very Good H     SI1     61.9  55    337   4.07 4.11 2.53
9     0.22  Fair      E     VS2     65.1  61    337   3.87 3.78 2.49
10    0.23  Very Good H     VS1     59.4  61    338   4.00 4.05 2.39
11    0.30  Good      J     SI1     64.0  55    339   4.25 4.28 2.73
12    0.23  Ideal     J     VS1     62.8  56    340   3.93 3.90 2.46
13    0.22  Premium   F     SI1     60.4  61    342   3.88 3.84 2.33
14    0.31  Ideal     J     SI2     62.2  54    344   4.35 4.37 2.71
15    0.20  Premium   E     SI2     60.2  62    345   3.79 3.75 2.27
16    0.32  Premium   E     I1      60.9  58    345   4.38 4.42 2.68
17    0.30  Ideal     I     SI2     62.0  54    348   4.31 4.34 2.68
18    0.30  Good      J     SI1     63.4  54    351   4.23 4.29 2.70
19    0.30  Good      J     SI1     63.8  56    351   4.23 4.26 2.71
20    0.30  Very Good J     SI1     62.7  59    351   4.21 4.27 2.66
21    0.30  Good      I     SI2     63.3  56    351   4.26 4.30 2.71
22    0.23  Very Good E     VS2     63.8  55    352   3.85 3.92 2.48
23    0.23  Very Good H     VS1     61.0  57    353   3.94 3.96 2.41
24    0.31  Very Good J     SI1     59.4  62    353   4.39 4.43 2.62
25    0.31  Very Good J     SI1     58.1  62    353   4.44 4.47 2.59
26    0.23  Very Good G     VVS2    60.4  58    354   3.97 4.01 2.41
27    0.24  Premium   I     VS1     62.5  57    355   3.97 3.94 2.47
28    0.30  Very Good J     VS2     62.2  57    357   4.28 4.30 2.67
29    0.23  Very Good D     VS2     60.5  61    357   3.96 3.97 2.40
30    0.23  Very Good F     VS1     60.9  57    357   3.96 3.99 2.42
⋮     ⋮     ⋮         ⋮     ⋮       ⋮     ⋮     ⋮     ⋮    ⋮    ⋮   
53911 0.70  Premium   E     SI1     60.5  58    2753  5.74 5.77 3.48
53912 0.57  Premium   E     IF      59.8  60    2753  5.43 5.38 3.23
53913 0.61  Premium   F     VVS1    61.8  59    2753  5.48 5.40 3.36
53914 0.80  Good      G     VS2     64.2  58    2753  5.84 5.81 3.74
53915 0.84  Good      I     VS1     63.7  59    2753  5.94 5.90 3.77
53916 0.77  Ideal     E     SI2     62.1  56    2753  5.84 5.86 3.63
53917 0.74  Good      D     SI1     63.1  59    2753  5.71 5.74 3.61
53918 0.90  Very Good J     SI1     63.2  60    2753  6.12 6.09 3.86
53919 0.76  Premium   I     VS1     59.3  62    2753  5.93 5.85 3.49
53920 0.76  Ideal     I     VVS1    62.2  55    2753  5.89 5.87 3.66
53921 0.70  Very Good E     VS2     62.4  60    2755  5.57 5.61 3.49
53922 0.70  Very Good E     VS2     62.8  60    2755  5.59 5.65 3.53
53923 0.70  Very Good D     VS1     63.1  59    2755  5.67 5.58 3.55
53924 0.73  Ideal     I     VS2     61.3  56    2756  5.80 5.84 3.57
53925 0.73  Ideal     I     VS2     61.6  55    2756  5.82 5.84 3.59
53926 0.79  Ideal     I     SI1     61.6  56    2756  5.95 5.97 3.67
53927 0.71  Ideal     E     SI1     61.9  56    2756  5.71 5.73 3.54
53928 0.79  Good      F     SI1     58.1  59    2756  6.06 6.13 3.54
53929 0.79  Premium   E     SI2     61.4  58    2756  6.03 5.96 3.68
53930 0.71  Ideal     G     VS1     61.4  56    2756  5.76 5.73 3.53
53931 0.71  Premium   E     SI1     60.5  55    2756  5.79 5.74 3.49
53932 0.71  Premium   F     SI1     59.8  62    2756  5.74 5.73 3.43
53933 0.70  Very Good E     VS2     60.5  59    2757  5.71 5.76 3.47
53934 0.70  Very Good E     VS2     61.2  59    2757  5.69 5.72 3.49
53935 0.72  Premium   D     SI1     62.7  59    2757  5.69 5.73 3.58
53936 0.72  Ideal     D     SI1     60.8  57    2757  5.75 5.76 3.50
5393

In [61]:
diaDT[,mean(price), by=cut]
# 이런 식으로도 할 수 있겠다. 
# data table은 거의 가장 빠른 방법으로 통한다.

cut       V1      
1 Ideal     3457.542
2 Premium   4584.258
3 Good      3928.864
4 Very Good 3981.760
5 Fair      4358.758

In [66]:
# 파이프에 대해 배워보자.

diamonds %>% head %>% dim # 이렇게 하는 게 빠르다는 얘기가 있다. 

[1]  6 10

In [71]:
require(dplyr)
require(plyr)

In [72]:
diamonds %>% group_by(cut) %>% dplyr::summarize(Price=mean(price))

cut       Price   
1 Fair      4358.758
2 Good      3928.864
3 Very Good 3981.760
4 Premium   4584.258
5 Ideal     3457.542

dplyr를 데이터베이스에서 사용해보자.

In [73]:
download.file("http://www.jaredlander.com/data/diamond.db", destfile="diamonds.db", method="curl")

In [74]:
require(dplyr)

In [76]:
diaDBSource <- src_mysql("diamonds.db")

ERROR: Error: The RMySQL package is required to connect to MySQL/MariaDB.
Please install it with `install.packages("RMySQL")`


In [ ]:
diaDB <- tbl(diaDBSource, "diamonds")

In [ ]:
diaDB %>% group_by(cut) %>% dplyr::summarize(price=mean(price))
# 이런식으로 데이터베이스에 바로 읽어오면서 
# 우리가 원하는 연산을 바로 해줄 수도 있겠다. 

In [77]:
install.packages("RMySQL")

Installing package into ‘/home/wonseok/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)

Warning message in install.packages("RMySQL"):
“installation of package ‘RMySQL’ had non-zero exit status”
